services:
  juno-satellite:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
    volumes:
      - juno_satellite:/juno/.juno
      - ./<JUNO_DEV_CONFIG>:/juno/<JUNO_DEV_CONFIG>
      - ./target/deploy:/juno/target/deploy/
    environment:
      - TZ=<TIME_ZONE>

volumes:
  juno_satellite:
