import {join} from 'node:path';
import {DEVELOPER_PROJECT_SATELLITE_PATH} from './dev.constants';

export const SATELLITE_DID_FILE = join(DEVELOPER_PROJECT_SATELLITE_PATH, 'satellite.did');
export const EXTENSION_DID_FILE_NAME = 'satellite_extension.did';
export const SATELLITE_CUSTOM_DID_FILE = join(
  DEVELOPER_PROJECT_SATELLITE_PATH,
  EXTENSION_DID_FILE_NAME
);

export const AUTO_GENERATED = `// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.`;
