export const DEFAULT_SATELLITE_HEAP_WASM_MEMORY_LIMIT = 1_073_741_824n;
export const DEFAULT_SATELLITE_FREEZING_THRESHOLD = 31_104_000n;

export const DEFAULT_RESERVED_CYCLES_LIMIT = 5_000_000_000_000n;
export const DEFAULT_LOG_VISIBILITY = "controllers";
export const DEFAULT_MEMORY_ALLOCATION = 0n;
export const DEFAULT_COMPUTE_ALLOCATION = 0n;
